---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_ubuntu
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    ansible_connection: docker
    ansible_user: root
  - name: instance_oraclelinux8
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
    ansible_connection: docker
    ansible_user: root
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
