---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance_ubuntu
    image: docker.io/library/ubuntu:22.04
    privileged: true
    command: sleep infinity   # Чтобы контейнер не завершался
  - name: instance_oraclelinux8
    image: docker.io/oraclelinux:8-slim
    privileged: true
    command: sleep infinity
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_SCENARIO_DIRECTORY}/converge.yml
scenario:
  name: podman-test
verifier:
  name: ansible
lint: yamllint
